apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: aicore-exe-pca
  annotations:
    scenarios.ai.sap.com/description: "aicore-serve-pca"
    scenarios.ai.sap.com/name: "aicore-serve-pca"
    executables.ai.sap.com/description: "aicore-exe-pca"
    executables.ai.sap.com/name: "aicore-exe-pca"
  labels:
    scenarios.ai.sap.com/id: "aicore-serve-pca"
    ai.sap.com/version: "1.0.0"
spec:
  template:
    apiVersion: "serving.kubeflow.org/v1beta1"
    metadata:
      labels: |
        ai.sap.com/resourcePlan: infer.s
    spec: |
      predictor:
        imagePullSecrets:
          - name: gcpsecretran
        containers:
        - name: kfserving-container
          image: "321880606331.dkr.ecr.us-east-1.amazonaws.com/scikit-runit-demo:latest"
          ports:
            - containerPort: 8080
              protocol: TCP
