apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: aicore-exe-pca-gcp
  annotations:
    scenarios.ai.sap.com/description: "aicore-serve-pca-gcp"
    scenarios.ai.sap.com/name: "aicore-serve-pca-gcp"
    executables.ai.sap.com/description: "aicore-exe-pca-gcp"
    executables.ai.sap.com/name: "aicore-exe-pca-gcp"
  labels:
    scenarios.ai.sap.com/id: "aicore-serve-pca-gcp"
    ai.sap.com/version: "1.0.0"
spec:
  template:
    apiVersion: "serving.kubeflow.org/v1beta1"
    metadata:
      labels: |
        ai.sap.com/resourcePlan: infer.s
    spec: |
      predictor:
        imagePullSecrets:
          - name: gcpsecretran
        containers:
        - name: kfserving-container
          image: "gcr.io/sap-ti-ci-sce/gcp-ai-core:v3"
          ports:
            - containerPort: 5060
              protocol: TCP
